baseURL: "https://dkermer.github.io/tutorials"
languageCode: en-us
defaultContentLanguage: en
title: "Debby's Posts"
theme: cupper_revised
googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: A collection of tutorials, articles, and posts about topics that interest me. 
  homeMetaContent: Musings on research methods, statistics, software and programming. .
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). 
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
 # codePenUser: someUser
 # katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    startLevel: 2
